name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 8.0.x

            # Install dotnet wasm buildtools workload
            - name: Install .NET WASM Build Tools
              run: dotnet workload install wasm-tools
            
            - name: Publish .NET Core Project
              run: dotnet publish MudExample/MudExample.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

            - name: copy index.html to 404.html
              run: cp dist/Web/wwwroot/index.html dist/Web/wwwroot/404.html

            # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
            - name: Change base-tag in index.html from / to mudexample
              run: sed -i 's/<base href="\/" \/>/<base href="\/mudexample\/" \/>/g' dist/Web/wwwroot/index.html              
              
            - name: Add .nojekyll file
              run: touch dist/Web/wwwroot/.nojekyll              
              
            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  GITHUB_TOKE: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: dist/Web/wwwroot
